# fly.toml app configuration file generated for teknologi-umum-bot on 2024-06-23T10:04:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teknologi-umum-bot'
primary_region = 'ams'

[build]

[[vm]]
size = 'shared-cpu-1x'
